# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hardikkaworkspace
useDotenv: true

# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: chatapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: chatapp

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

# Environment variables

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

#aws credentials

functions:
  matthu_query:
    handler: index.matthu_query
    events:
      - httpApi:
          path: /matthu
          method: post
  ai_twin_reply:
    handler: index.ai_twin_reply
    events:
      - httpApi:
          path: /twin
          method: post
  arena:
    handler: index.arena
    events:
      - httpApi:
          path: /arena
          method: post
  create_group:
    handler: index.create_group
    events:
      - httpApi:
          path: /create_group
          method: post
  add_members:
    handler: index.add_members
    events:
      - httpApi:
          path: /add_members
          method: post
  load_app_data:
    handler: index.load_app_data
    events:
      - httpApi:
          path: /load_app_data
          method: post
  generate_summary:
    handler: index.generate_summary
    events:
      - httpApi:
          path: /summary
          method: post
  register_user:
    handler: index.register_user
    events:
      - httpApi:
          path: /register
          method: post
  bye:
    handler: index.bye
    events:
      - httpApi:
          path: /bye
          method: get

  login_user:
    handler: index.login_user
    events:
      - httpApi:
          path: /login
          method: post
    